config/routes.rb
Rails.application.routes.draw do
  get 'web_cafes/top'
  get 'web_cafes/news'
  get 'web_cafes/contact'
  get 'web_cafes/menu'
  root 'web_cafes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/web_cafes_controller.rb
class WebCafesController < ApplicationController
  def top
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web_cafes_helper.rb
module WebCafesHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="small text-center" style="margin: 50px 0;">
		Copyright © 2020 Web-Cafe</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCafe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header">
      <%= render "layouts/header" %>
    </div>
    <%= yield %>
    <div id="footer">
      <%=render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/web_cafes/top.html.erb
<header>
	<div class="big-bg">
	<header class="header-content wrapper">
		<div class="logo"><%= image_tag "logo.jpg"  %></div>
		<nav>
			<ul class="main-nav">
				<li class="item"><%= link_to "NEWS" %></li>
				<li class="item"><%= link_to "CONTACT" %></li>
				<li class="item"><%= link_to "MENU" %></li>
			</ul>
		</nav>
	</div>
</header>
<div class="top-content">
	<h3>We'll Make Your Day</h3>
	<p>オシャレなカフェで癒されてみませんか？　無添加の食材で体の中からリフレッシュ。</p>
	<div class="menu-button">
		<%= link_to "メニューを見る", web_cafes_menu_path, class: "btn btn-primary" %>
	</div>
</div>
</div>